project:
  type: website
  output-dir: _site

website:
  title: "Rafael Cond√© Gomes"
  site-url: "https://condeg0.github.io/RafaelCondeGomes" # Explicitly sets the base URL
  navbar:
    left:
      - href: index.qmd
        text: Home
      # Additional links here!!!

execute:
  freeze: auto
